/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ippro12;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author pc
 */
public class sign extends javax.swing.JFrame {

    /**
     * Creates new form sign
     */
    public sign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        p = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pc = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        u1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME   TO   LIBRARY    Sign-Up");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 380, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 79, 157, 23);

        n.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(n);
        n.setBounds(180, 79, 210, 30);

        i.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(i);
        i.setBounds(180, 120, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Student ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 157, 23);

        d.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(d);
        d.setBounds(180, 161, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date Of Birth");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 161, 157, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 202, 157, 23);

        a.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(180, 202, 210, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Phone No.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 243, 157, 23);

        pn.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(pn);
        pn.setBounds(180, 243, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Passcode");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 330, 157, 23);

        pc.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(pc);
        pc.setBounds(180, 330, 210, 30);

        signInButton.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        signInButton.setText("Sign Up");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInButton);
        signInButton.setBounds(90, 380, 213, 49);

        u1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(u1);
        u1.setBounds(180, 290, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Username");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 290, 157, 23);
        getContentPane().add(pic);
        pic.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>                        

    private void aActionPerformed(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon("D:\\IP\\signup.JPG"));
    }                                 

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int i1 = Integer.parseInt(i.getText());
        String u2 = u1.getText();
        String n1 = n.getText();
        String d1 = d.getText();
        String pc1 = pc.getText();
        String a1 = a.getText();
        String pn1 = pn.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "<your password>"); 
            Statement stm = con.createStatement();
            
            String q = "SELECT * FROM student;";
            ResultSet r= stm.executeQuery(q);
            while (r.next()){
                String u3 = r.getString("user");
                if (u2.equals(u3)){
                    JOptionPane.showMessageDialog(null, "This user-name is already reserved! \nPlease enter some other user-name!", "Error", 1);
                    u1.setText("");
                    u2 = "";
                    break;
                }
            }
            
            if (u2.equals("") || n1.equals("") || d1.equals("") || pc1.equals("") || a1.equals("") || pn1.equals("") || i.getText().equals("")){
                JOptionPane.showMessageDialog(null, "You cannot leave any field empty!", "Error", 2);
            } else{
            String q1 = "INSERT INTO student VALUES("+i1+" ,'"+u2+"' ,'"+n1+"', '"+d1+"', '"+pc1+"', '"+a1+"', "+pn1+", null, null, null, null);";
            stm.executeUpdate(q1);
            JOptionPane.showMessageDialog(null, "Your account is created! \nWelcome to the Advanced Libray!!! \nEnjoy!!!!!!!!!!!", "Welcome!!", 1);
            }
            
            stm.close();
            con.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JTextField a;
    private javax.swing.JTextField d;
    private javax.swing.JTextField i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n;
    private javax.swing.JLabel p;
    private javax.swing.JTextField pc;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField pn;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField u1;
    // End of variables declaration                   
}
